name:                random-quote
version:             0.0.1
github:              "TheMC47/random-quote"
license:             MIT
author:              "Yecine Megdiche"
maintainer:          "yecine.megdiche@gmail.com"
copyright:           "2020 Yecine Megdiche"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/TheMC47/random-quote>

dependencies:
- base >= 4.7 && < 5
- random
- QuickCheck

library:
  source-dirs: src

executables:
  random-quote:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - random
    - QuickCheck
    - random-quote

tests:
  random-quote-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - random-quote
    - QuickCheck
